src/app/App.jsx
src/app/style.module.css
src/pages/Preview.jsx
src/pages/Write.jsx

- 미리보기 버튼 클릭 시 미리보기 페이지로 전환
- 돌아가기 버튼 클릭 시 이력서 작성 페이지로 전환

Feat: 메인 페이지, 미리보기페이지, 이력서 작성페이지 기초 작업

---

src/components/Profile/ProfileInput.jsx
src/components/Profile/ProfileInput.module.css

Feat: ProfilInput component UI 작성

---

src/components/Intro/IntroInput.jsx
src/components/Intro/IntroInput.module.css

Feat: IntroInput component UI 작성

---

src/components/Profile/ProfileOutput.jsx
src/components/Profile/ProfileOutput.module.css
src/pages/Preview.jsx
src/styles/reset.css

Feat: ProfileOutput component UI 작성

---

src/components/Skills/SkillsOutput.jsx
src/components/Skills/SkillsOutput.module.css
src/pages/Preview.jsx

Feat: SkillsOutput component UI 작성

---

src/components/Intro/IntroInput.jsx
src/components/Profile/ProfileInput.jsx
src/styles/reset.css

- 글자 수 카운팅 기능 구현
- 이벤트 핸들러 함수명 통일
- Intro input창 width 수정 => reset.css 모든 요소에 box-sizing: border-box; 추가
- <img width="357" alt="스크린샷 2023-06-07 오후 4 30 00" src="https://github.com/weniv/Resume/assets/94890646/7ffa3a5d-8006-4e08-913f-ad845b7523f5">
- <img width="145" alt="스크린샷 2023-06-07 오후 4 30 05" src="https://github.com/weniv/Resume/assets/94890646/aa726d0f-df0f-4f91-a19a-48c1c56954f9">

Feat: Intro input창 onChange될 때 글자 수 카운팅 기능 구현

---

src/components/Skills/SkillsInput.jsx

Feat: 스킬 추가 기능 구현

---

src/app/App.jsx
src/components/Profile/ProfileInput.jsx
src/pages/Write.jsx

- 임시 저장 버튼 클릭 시 로컬스토리지에 데이터 업데이트
- useState props로 넘겨서 컴포넌트에서 데이터 업데이트 가능
[계획]
- 컴포넌트에서 useEffect사용하여 데이터 변경 있을 때 마다 업데이트 되도록 구현 생각 중
- 임시 저장되는 동안 loading 애니메이션 추가 예정
- 버튼 hover시 색상 변경 예정

feat: 임시저장 기능 추가

---

src/components/Skills/SkillsInput.module.css

intro를 제외한 다른 항목과 통일해 `margin-left` 속성 추가했습니다.

Style: Skills 컴포넌트 좌측 여백 추가

---

src/components/Experience/ExperienceOutput.jsx

- Input에서는 사용자가 작성한 순서 유지
- Output에서 값이 없는 데이터 삭제 및 최신순 정렬

Feat: ExperienceOutput 최신 순 정렬

---

src/components/Url/url.module.css

- url 이미지의 버튼만 크기가 달라 다른 요소와 동일하게 변경

Feat/UrlStyle: 버튼 내부 이미지 스타일 변경

---

src/components/Url/UrlInput.jsx
src/components/Url/UrlOutput.jsx

Edit: 텍스트 변경

---

README.md
src/components/Experience/experience.module.css
src/components/Url/UrlInput.jsx
src/components/Url/UrlOutput.jsx

- 리드미 수정
- URL 입력 페이지: label-input 연결될 수 있도록 처리
- Url 이동 시 base_url과 연결되지 않도록 validation 추가
- 연도 드롭다운 메뉴 가로 스크롤 제거 (window)

Feat/url: 피드백 반영 및 리드미 수정

---

src/app/App.jsx
src/components/Experience/ExperienceInput.jsx
src/components/Experience/ExperienceOutput.jsx
src/components/Experience/experience.module.css
src/components/ExportPdf/ExportPdf.jsx
src/components/Url/UrlOutput.jsx
src/components/Url/url.module.css

- 항목의 값이 모두 비어있을 때만 Output 출력 제거
- 데이터가 없는 경우에 섹션 미출력
- Experience 날짜 YYYY-MM 형식으로 변경

Feat/detail modif: 회의 피드백 반영

---

src/app/App.jsx

resumeData 초기화
- 로컬 스토리지에 data (O) - 해당 데이터 / (X) - dummyData
- 추후에 dummyData는 값이 없는 initialValue로 변경할 예정입니다

Feat: 로컬 스토리지에 data가 있는 경우 해당 값으로 resumeData를 초기화

---

src/app/App.jsx
src/components/Certificate/CertificateInput.jsx
src/components/Certificate/CertificateInput.module.css
src/components/Certificate/CertificateOuput.module.css
src/components/Certificate/CertificateOutput.jsx
src/components/Education/EducationInput.jsx
src/components/Education/EducationInput.module.css
src/components/Education/EducationOutput.jsx
src/components/Education/EducationOutput.module.css

- Preview, Write 페이지 내 타입 변경 사항 반영
- input 타입 변경에 따른 포맷팅 기능 추가

Feat: Education, Certification input 타입 변경

---

src/components/Certificate/CertificateOutput.jsx
src/components/Education/EducationOutput.jsx

입력값 2개 중 하나 누락된 경우 처리는 따로 추가할 예정입니다.

Feat: Cert, Edu 입력값 있는 경우만 Output 페이지 출력

---

package-lock.json
package.json
src/app/App.jsx
src/app/style.module.css
src/pages/Preview.jsx
src/pages/preview.module.css

- 프린트 버튼을 누르면 브라우저 출력 기능으로 pdf를 저장하거나 출력할 수 있습니다.
-> 다른 라이브러리의 경우 html -> canvas -> pdf 처리라 이미지화 되면서 링크 이동 불가
- 출력 영역 여백을 위한 스타일 수정

Feat/exportPDF : PDF 출력 기능

---

src/components/Certificate/CertificateOuput.module.css
src/components/Certificate/CertificateOutput.jsx
src/components/Education/EducationOutput.jsx
src/components/Education/EducationOutput.module.css

- 날짜, 내용 입력 값 모두 없을 때: Output에서 표시 제외
- 날짜, 내용 입력 값 중 하나만 없을 때: Output에서 해당 누락 값 '-' 표시

Feat: Cert, Edu 입력 값 하나일 때 output 스타일 추가

---

src/components/Certificate/CertificateInput.module.css
src/components/Education/EducationInput.module.css

4차 회의 (6.20) 때 논의했던 대로 상단 이미지처럼 테두리 스타일을 통일했습니다.

Style: Certitification, Education 포커스 상태 테두리 스타일 통일

---

src/app/App.jsx
src/components/Profile/ProfileInput.jsx
src/pages/Preview.jsx

boolean -> 기존 string 타입으로 변경했습니다.

Fix: newcomer 타입 변경

---

src/components/Profile/ProfileOutput.jsx
src/components/Profile/ProfileOutput.module.css

Fix: 프로필 이미지 없을 때 UI 수정

---

src/app/App.jsx

- 추후 입력한 데이터가 없을 때 해당 이미지가 보여지도록 변경
- api로 응답받은 이미지 주소 추가해두었습니다

Feat: 프로필 기본 이미지로 변경

---

src/components/Career/CareerInput.jsx
src/components/Career/CareerInput.module.css
src/components/Career/CareerOutput.module.css

- input focus시 border 겹치는 현상 수정
- 담당업무 input/output 부분 line-height 및 margin 추가하여 공백적용
- label과 input 연결

style: career 스타일 수정

---

src/app/App.jsx
src/components/Career/CareerInput.jsx
src/components/Project/ProjectInput.jsx
src/components/Project/ProjectInput.module.css
src/components/Project/ProjectOutput.jsx
src/components/Project/ProjectOutput.module.css

- 프로젝트 설명 input/output 여백 추가
- 삭제버튼과 텍스트가 겹치지 않도록 수정
- 드롭다운시 화살표 방향 변경되도록 수정

style: project style 수정

---

src/components/Profile/ProfileInput.jsx
src/components/Profile/ProfileInput.module.css

- 기본 이미지로 변경
- 이미지가 있을 때에만 삭제 버튼 활성화

Feat: 프로필 이미지 삭제 기능 추가

---

src/components/Intro/IntroInput.jsx

Feat: Textarea 입력과 setState 수정

---

src/components/Project/ProjectInput.jsx

Feat: 프로젝트 label-input 연결 추가

---

src/components/Certificate/CertificateInput.module.css
src/components/Education/EducationInput.module.css
src/components/Experience/ExperienceInput.module.css
src/components/Url/UrlInput.module.css

- 윈도우에서 달력에 의해 입력창이 잘려보이는 현상이 있어 너비 변경
- url 너비와 다른 항목 너비 차이로 어색해보여 너비 변경

Style: input month 너비 수정

---

src/components/Intro/IntroOutput.module.css
src/components/Profile/ProfileOutput.jsx
src/components/Profile/ProfileOutput.module.css

- Intorudction 전체 너비로 변경(오른쪽 여백 제거)
- 프로필 정보 max-width 값 지정으로, 커밋 이미지에 의해 프로필 이미지 크기가 변경되지 않도록 설정

Style: Profile 스타일 변경
